# Generated by Django 5.2.17 on 2026-08-10 21:14

import apps.core.models
import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HowToStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('title_uk', models.CharField(max_length=200, verbose_name='title, uk')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='title, ru')),
                ('text_uk', models.TextField(blank=True, verbose_name='text, uk')),
                ('text_ru', models.TextField(blank=True, verbose_name='text, ru')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'how to order step',
                'verbose_name_plural': 'how to order steps',
                'ordering': ['order', 'id'],
            },
            bases=(apps.core.models.TranslatedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_primary', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='main phone')),
                ('phone_secondary', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='second phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('viber_url', models.URLField(blank=True, verbose_name='Viber link')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram link')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram link')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook link')),
                ('address_uk', models.CharField(blank=True, max_length=300, verbose_name='address, uk')),
                ('address_ru', models.CharField(blank=True, max_length=300, verbose_name='address, ru')),
                ('landmark_uk', models.CharField(blank=True, max_length=300, verbose_name='landmark, uk')),
                ('landmark_ru', models.CharField(blank=True, max_length=300, verbose_name='landmark, ru')),
                ('parking_uk', models.CharField(blank=True, max_length=300, verbose_name='parking, uk')),
                ('parking_ru', models.CharField(blank=True, max_length=300, verbose_name='parking, ru')),
                ('map_embed_url', models.URLField(blank=True, max_length=500, verbose_name='map embed URL')),
                ('map_directions_url', models.URLField(blank=True, max_length=500, verbose_name='directions URL')),
                ('working_hours_uk', models.TextField(blank=True, verbose_name='working hours, uk')),
                ('working_hours_ru', models.TextField(blank=True, verbose_name='working hours, ru')),
                ('accepting_orders', models.BooleanField(default=True, verbose_name='accepting orders')),
                ('not_accepting_message_uk', models.CharField(blank=True, max_length=300, verbose_name='not accepting message, uk')),
                ('not_accepting_message_ru', models.CharField(blank=True, max_length=300, verbose_name='not accepting message, ru')),
                ('banner_enabled', models.BooleanField(default=False, verbose_name='banner enabled')),
                ('banner_text_uk', models.CharField(blank=True, max_length=300, verbose_name='banner text, uk')),
                ('banner_text_ru', models.CharField(blank=True, max_length=300, verbose_name='banner text, ru')),
                ('banner_url', models.URLField(blank=True, verbose_name='banner link')),
                ('banner_until', models.DateTimeField(blank=True, null=True, verbose_name='banner until')),
                ('prices_enabled', models.BooleanField(default=False, verbose_name='prices enabled')),
                ('watermark_image', models.ImageField(blank=True, upload_to='site/', verbose_name='watermark')),
                ('watermark_opacity', models.FloatField(default=0.35, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='watermark opacity')),
                ('watermark_position', models.CharField(choices=[('bottom_right', 'Bottom right'), ('bottom_left', 'Bottom left'), ('center', 'Center')], default='bottom_right', max_length=20, verbose_name='watermark position')),
                ('watermark_scale', models.FloatField(default=0.18, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1.0)], verbose_name='watermark scale')),
                ('og_default_image', models.ImageField(blank=True, upload_to='site/', verbose_name='default OG image')),
                ('analytics_ga_id', models.CharField(blank=True, max_length=50, verbose_name='GA4 measurement id')),
                ('site_name_uk', models.CharField(blank=True, max_length=100, verbose_name='site name, uk')),
                ('site_name_ru', models.CharField(blank=True, max_length=100, verbose_name='site name, ru')),
                ('hero_title_uk', models.CharField(blank=True, max_length=200, verbose_name='hero title, uk')),
                ('hero_title_ru', models.CharField(blank=True, max_length=200, verbose_name='hero title, ru')),
                ('hero_subtitle_uk', models.CharField(blank=True, max_length=300, verbose_name='hero subtitle, uk')),
                ('hero_subtitle_ru', models.CharField(blank=True, max_length=300, verbose_name='hero subtitle, ru')),
                ('hero_image', models.ImageField(blank=True, upload_to='site/', verbose_name='hero image')),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
            bases=(apps.core.models.TranslatedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='slug')),
                ('title_uk', models.CharField(max_length=200, verbose_name='title, uk')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='title, ru')),
                ('body_uk', models.TextField(blank=True, verbose_name='body, uk')),
                ('body_ru', models.TextField(blank=True, verbose_name='body, ru')),
                ('seo_title_uk', models.CharField(blank=True, max_length=200, verbose_name='SEO title, uk')),
                ('seo_title_ru', models.CharField(blank=True, max_length=200, verbose_name='SEO title, ru')),
                ('seo_description_uk', models.CharField(blank=True, max_length=300, verbose_name='SEO description, uk')),
                ('seo_description_ru', models.CharField(blank=True, max_length=300, verbose_name='SEO description, ru')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'static page',
                'verbose_name_plural': 'static pages',
                'ordering': ['slug'],
            },
            bases=(apps.core.models.TranslatedMixin, models.Model),
        ),
    ]
