# Generated by Django 5.2.17 on 2026-08-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_text_ru',
            field=models.CharField(blank=True, max_length=300, verbose_name='delivery, ru'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_text_uk',
            field=models.CharField(blank=True, max_length=300, verbose_name='delivery, uk'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pickup_text_ru',
            field=models.CharField(blank=True, max_length=300, verbose_name='pickup, ru'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pickup_text_uk',
            field=models.CharField(blank=True, max_length=300, verbose_name='pickup, uk'),
        ),
    ]
