# Generated by Django 5.2.17 on 2026-08-11 10:39

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_add_photo_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='UA', verbose_name='phone')),
                ('preferred_contact', models.CharField(choices=[('phone', 'Phone call'), ('viber', 'Viber'), ('telegram', 'Telegram')], default='phone', max_length=20, verbose_name='preferred contact')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='event date')),
                ('budget_text', models.CharField(blank=True, max_length=50, verbose_name='budget')),
                ('comment', models.CharField(blank=True, max_length=1000, verbose_name='comment')),
                ('work_article', models.PositiveIntegerField(blank=True, null=True, verbose_name='work number')),
                ('favorites_articles', models.JSONField(blank=True, default=list, verbose_name='favourites')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('done', 'Done'), ('spam', 'Spam')], default='new', max_length=20, verbose_name='status')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='came from')),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('consent', models.BooleanField(default=False, verbose_name='consent')),
                ('notified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notify_attempts', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='catalog.work', verbose_name='work')),
            ],
            options={
                'verbose_name': 'enquiry',
                'verbose_name_plural': 'enquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='lead_status_created_idx')],
            },
        ),
    ]
