# Generated by Django 5.2.17 on 2026-08-11 19:22

import apps.core.models
import config.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_add_photo_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('title_uk', models.CharField(max_length=200, verbose_name='title, uk')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='title, ru')),
                ('excerpt_uk', models.CharField(blank=True, max_length=300, verbose_name='excerpt, uk')),
                ('excerpt_ru', models.CharField(blank=True, max_length=300, verbose_name='excerpt, ru')),
                ('body_uk', models.TextField(blank=True, verbose_name='body, uk')),
                ('body_ru', models.TextField(blank=True, verbose_name='body, ru')),
                ('cover', models.ImageField(blank=True, storage=config.storages.public_storage, upload_to='blog/', verbose_name='cover')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='views')),
                ('seo_title_uk', models.CharField(blank=True, max_length=200, verbose_name='SEO title, uk')),
                ('seo_title_ru', models.CharField(blank=True, max_length=200, verbose_name='SEO title, ru')),
                ('seo_description_uk', models.CharField(blank=True, max_length=300, verbose_name='SEO description, uk')),
                ('seo_description_ru', models.CharField(blank=True, max_length=300, verbose_name='SEO description, ru')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_works', models.ManyToManyField(blank=True, related_name='posts', to='catalog.work', verbose_name='related works')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': [models.OrderBy(models.F('published_at'), descending=True, nulls_last=True), '-id'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='post_status_published_idx')],
            },
            bases=(apps.core.models.TranslatedMixin, models.Model),
        ),
    ]
