# Generated by Django 5.1.15 on 2026-08-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PingRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nonce', models.CharField(max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['nonce'], name='common_ping_nonce_4bd653_idx')],
            },
        ),
    ]
