# Data migration (not autogenerated): seeds a celery-beat schedule for
# common.ping so "beat запускает расписание" (S0.6/DEV.md §4 checklist)
# is true out of the box instead of needing a manual admin step.
# RunPython with a reverse operation, per DEV.md §13.

from __future__ import annotations

from typing import Any

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

PERIODIC_TASK_NAME = "common.ping heartbeat"


def seed_ping_schedule(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    interval_schedule_model = apps.get_model("django_celery_beat", "IntervalSchedule")
    periodic_task_model = apps.get_model("django_celery_beat", "PeriodicTask")

    schedule, _ = interval_schedule_model.objects.get_or_create(every=5, period="minutes")
    periodic_task_model.objects.get_or_create(
        name=PERIODIC_TASK_NAME,
        defaults={
            "task": "common.ping",
            "interval": schedule,
            "kwargs": '{"payload": {"nonce": "beat-heartbeat"}}',
        },
    )


def remove_ping_schedule(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    periodic_task_model = apps.get_model("django_celery_beat", "PeriodicTask")
    periodic_task_model.objects.filter(name=PERIODIC_TASK_NAME).delete()


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [
        ("common", "0001_initial"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations: list[Any] = [
        migrations.RunPython(seed_ping_schedule, remove_ping_schedule),
    ]
