"""Section 8: task names, payload validation, idempotency."""

from datetime import timedelta

import pytest
from django.utils import timezone
from pydantic import ValidationError

from apps.core.contracts import EmptyPayload
from apps.core.models import SiteSettings
from apps.core.tasks import expire_banner
from config.celery import RetryTask, app


def test_task_names_are_explicit() -> None:
    """Section 8: an autogenerated name would carry the `apps.` prefix and
    drift away from the beat schedule."""
    import apps.catalog.tasks  # noqa: F401
    import apps.leads.tasks  # noqa: F401
    import apps.reviews.tasks  # noqa: F401

    expected = {
        "core.expire_banner",
        "catalog.generate_renditions",
        "catalog.regenerate_all_renditions",
        "catalog.flush_view_counters",
        "leads.notify_new_lead",
        "reviews.notify_new_review",
    }
    assert expected <= set(app.tasks)
    assert expire_banner.name == "core.expire_banner"


def test_the_demo_task_is_gone() -> None:
    """Section 8.7 and the launch checklist: core.ping goes away."""
    assert "core.ping" not in app.tasks


def test_beat_entries_resolve_to_registered_tasks() -> None:
    assert app.conf.beat_schedule

    for name, entry in app.conf.beat_schedule.items():
        assert entry["task"] in app.tasks, f"{name} points at an unregistered task"
        assert "payload" in entry["kwargs"]


def test_invalid_payload_is_rejected_before_any_work() -> None:
    with pytest.raises(ValidationError):
        expire_banner(payload={"unexpected": 1})


def test_empty_payload_forbids_extras() -> None:
    assert EmptyPayload.model_validate({}) is not None

    with pytest.raises(ValidationError):
        EmptyPayload.model_validate({"lead_id": 1})


def test_retry_policy_matches_the_contract() -> None:
    assert RetryTask.max_retries == 5
    assert RetryTask.retry_backoff is True
    assert RetryTask.retry_backoff_max == 600
    assert RetryTask.retry_jitter is True
    assert expire_banner.max_retries == 5


def test_media_queue_is_routed_separately() -> None:
    assert app.conf.task_default_queue == "default"
    assert app.conf.task_routes["catalog.generate_renditions"] == {"queue": "media"}


@pytest.mark.django_db
def test_expire_banner_unticks_a_banner_whose_date_has_passed() -> None:
    site = SiteSettings.load()
    site.banner_enabled = True
    site.banner_text_uk = "Стара акція"
    site.banner_until = timezone.now() - timedelta(minutes=1)
    site.save()

    assert expire_banner(payload={}) is True

    site.refresh_from_db()
    assert site.banner_enabled is False


@pytest.mark.django_db
def test_expire_banner_is_idempotent() -> None:
    site = SiteSettings.load()
    site.banner_enabled = True
    site.banner_until = timezone.now() - timedelta(minutes=1)
    site.save()

    first = expire_banner(payload={})
    second = expire_banner(payload={})

    assert (first, second) == (True, False)
    site.refresh_from_db()
    assert site.banner_enabled is False


@pytest.mark.django_db
def test_expire_banner_leaves_a_live_banner_alone() -> None:
    site = SiteSettings.load()
    site.banner_enabled = True
    site.banner_until = timezone.now() + timedelta(days=1)
    site.save()

    assert expire_banner(payload={}) is False

    site.refresh_from_db()
    assert site.banner_enabled is True


@pytest.mark.django_db
def test_expire_banner_refuses_an_unexpected_payload() -> None:
    with pytest.raises(ValidationError):
        expire_banner(payload={"now": "today"})
