# Generated by Django 5.2.17 on 2026-08-11 09:41

import apps.core.models
import config.storages
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Section 5: articles come from a sequence. A rolled back transaction
        # does not hand the number back, and that is the wanted behaviour.
        migrations.RunSQL(
            sql="CREATE SEQUENCE IF NOT EXISTS work_article_seq START WITH 100 INCREMENT BY 1;",
            reverse_sql="DROP SEQUENCE IF EXISTS work_article_seq;",
        ),
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='slug')),
                ('name_uk', models.CharField(max_length=100, verbose_name='name, uk')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='name, ru')),
                ('filter_kind', models.CharField(choices=[('checkbox', 'Checkboxes'), ('color_swatch', 'Colour swatches')], default='checkbox', max_length=20, verbose_name='filter kind')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'tag group',
                'verbose_name_plural': 'tag groups',
                'ordering': ['order', 'id'],
            },
            bases=(apps.core.models.TranslatedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='slug')),
                ('name_uk', models.CharField(max_length=100, verbose_name='name, uk')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='name, ru')),
                ('description_uk', models.TextField(blank=True, verbose_name='description, uk')),
                ('description_ru', models.TextField(blank=True, verbose_name='description, ru')),
                ('cover', models.ImageField(blank=True, storage=config.storages.public_storage, upload_to='occasions/', verbose_name='cover')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('show_on_home', models.BooleanField(default=True, verbose_name='show on the home page')),
                ('seo_title_uk', models.CharField(blank=True, max_length=200, verbose_name='SEO title, uk')),
                ('seo_title_ru', models.CharField(blank=True, max_length=200, verbose_name='SEO title, ru')),
                ('seo_description_uk', models.CharField(blank=True, max_length=300, verbose_name='SEO description, uk')),
                ('seo_description_ru', models.CharField(blank=True, max_length=300, verbose_name='SEO description, ru')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'occasion',
                'verbose_name_plural': 'occasions',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='occasion_active_order_idx')],
            },
            bases=(apps.core.models.TranslatedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='slug')),
                ('name_uk', models.CharField(max_length=100, verbose_name='name, uk')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='name, ru')),
                ('color_hex', models.CharField(blank=True, max_length=7, verbose_name='colour')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='catalog.taggroup', verbose_name='group')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['order', 'id'],
            },
            bases=(apps.core.models.TranslatedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.PositiveIntegerField(editable=False, unique=True, verbose_name='article')),
                ('slug', models.SlugField(editable=False, max_length=200, unique=True, verbose_name='slug')),
                ('title_uk', models.CharField(blank=True, max_length=200, verbose_name='title, uk')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='title, ru')),
                ('description_uk', models.TextField(blank=True, verbose_name='description, uk')),
                ('description_ru', models.TextField(blank=True, verbose_name='description, ru')),
                ('composition_uk', models.CharField(blank=True, max_length=300, verbose_name='composition, uk')),
                ('composition_ru', models.CharField(blank=True, max_length=300, verbose_name='composition, ru')),
                ('size_text_uk', models.CharField(blank=True, max_length=100, verbose_name='size, uk')),
                ('size_text_ru', models.CharField(blank=True, max_length=100, verbose_name='size, ru')),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price from')),
                ('price_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price to')),
                ('currency', models.CharField(default='UAH', max_length=3, verbose_name='currency')),
                ('price_visible', models.BooleanField(default=False, verbose_name='show the price')),
                ('price_note_uk', models.CharField(blank=True, max_length=200, verbose_name='price note, uk')),
                ('price_note_ru', models.CharField(blank=True, max_length=200, verbose_name='price note, ru')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cost')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='status')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='pinned')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='views')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('seo_title_uk', models.CharField(blank=True, max_length=200, verbose_name='SEO title, uk')),
                ('seo_title_ru', models.CharField(blank=True, max_length=200, verbose_name='SEO title, ru')),
                ('seo_description_uk', models.CharField(blank=True, max_length=300, verbose_name='SEO description, uk')),
                ('seo_description_ru', models.CharField(blank=True, max_length=300, verbose_name='SEO description, ru')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occasions', models.ManyToManyField(blank=True, related_name='works', to='catalog.occasion', verbose_name='occasions')),
                ('tags', models.ManyToManyField(blank=True, related_name='works', to='catalog.tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'work',
                'verbose_name_plural': 'works',
                'ordering': ['-is_pinned', 'order', models.OrderBy(models.F('published_at'), descending=True, nulls_last=True), '-id'],
            },
            bases=(apps.core.models.TranslatedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', storage=config.storages.private_storage, upload_to='works/%Y/%m/', verbose_name='photo', width_field='width')),
                ('width', models.PositiveIntegerField(default=0, editable=False)),
                ('height', models.PositiveIntegerField(default=0, editable=False)),
                ('alt_uk', models.CharField(blank=True, max_length=200, verbose_name='alt text, uk')),
                ('alt_ru', models.CharField(blank=True, max_length=200, verbose_name='alt text, ru')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('is_main', models.BooleanField(default=False, verbose_name='main photo')),
                ('renditions_ready', models.BooleanField(default=False, editable=False, verbose_name='renditions ready')),
                ('renditions_version', models.CharField(blank=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.work', verbose_name='work')),
            ],
            options={
                'verbose_name': 'work photo',
                'verbose_name_plural': 'work photos',
                'ordering': ['order', 'id'],
            },
            bases=(apps.core.models.TranslatedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WorkImageRendition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset', models.CharField(choices=[('thumb', 'Thumbnail'), ('card', 'Card'), ('large', 'Large'), ('og', 'Link preview')], max_length=10, verbose_name='preset')),
                ('image_format', models.CharField(choices=[('avif', 'AVIF'), ('webp', 'WebP'), ('jpeg', 'JPEG')], max_length=10, verbose_name='format')),
                ('file', models.ImageField(storage=config.storages.public_storage, upload_to='renditions/%Y/%m/', verbose_name='file')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('bytes', models.PositiveIntegerField(default=0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='catalog.workimage', verbose_name='source')),
            ],
            options={
                'verbose_name': 'rendition',
                'verbose_name_plural': 'renditions',
                'ordering': ['preset', 'image_format'],
            },
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['status', 'published_at'], name='work_status_published_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['status', 'is_pinned', 'order'], name='work_status_pinned_idx'),
        ),
        migrations.AddConstraint(
            model_name='work',
            constraint=models.CheckConstraint(condition=models.Q(('price_to__isnull', True), ('price_from__isnull', True), ('price_to__gte', models.F('price_from')), _connector='OR'), name='price_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='workimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('work',), name='one_main_image_per_work'),
        ),
        migrations.AddConstraint(
            model_name='workimagerendition',
            constraint=models.UniqueConstraint(fields=('source', 'preset', 'image_format'), name='one_rendition_per_variant'),
        ),
    ]
