# Generated by Django 5.2.17 on 2026-08-11 09:58

import apps.catalog.services.images
import config.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workimage',
            name='image',
            field=models.ImageField(height_field='height', storage=config.storages.private_storage, upload_to='works/%Y/%m/', validators=[apps.catalog.services.images.validate_work_photo], verbose_name='photo', width_field='width'),
        ),
    ]
