# Generated by Django 5.2.17 on 2026-08-11 19:13

import apps.core.models
import config.storages
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_add_photo_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='name')),
                ('text_uk', models.TextField(blank=True, verbose_name='text, uk')),
                ('text_ru', models.TextField(blank=True, verbose_name='text, ru')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='rating')),
                ('photo', models.ImageField(blank=True, storage=config.storages.public_storage, upload_to='reviews/', verbose_name='photo')),
                ('source', models.CharField(choices=[('admin', 'Added by the owner'), ('site', 'Left on the site')], default='admin', max_length=10, verbose_name='source')),
                ('status', models.CharField(choices=[('pending', 'Waiting for moderation'), ('published', 'Published'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='status')),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='UA', verbose_name='phone for us')),
                ('is_featured', models.BooleanField(default=False, verbose_name='show on the home page')),
                ('consent', models.BooleanField(default=False, verbose_name='consent')),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('notified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notify_attempts', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='catalog.work', verbose_name='work')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ['-published_at', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='review_rating_range')],
            },
            bases=(apps.core.models.TranslatedMixin, models.Model),
        ),
    ]
